In [1]:
import polars as pl
from extract_and_transform import extract_and_transform
df = extract_and_transform()
df.head()

shape: (5, 78)
┌─────┬─────┬─────┬─────┬───┬─────┬─────┬───────┬───────┐
│ pho ┆ Lon ┆ Nat ┆ Pos ┆ … ┆ Con ┆ Tea ┆ Total ┆ Total │
│ toU ┆ gNa ┆ ion ┆ iti ┆   ┆ tra ┆ m   ┆ Menta ┆ Stats │
│ rl  ┆ me  ┆ ali ┆ ons ┆   ┆ ct  ┆ --- ┆ lity  ┆ ---   │
│ --- ┆ --- ┆ ty  ┆ --- ┆   ┆ End ┆ str ┆ ---   ┆ i64   │
│ str ┆ str ┆ --- ┆ lis ┆   ┆ s   ┆     ┆ i64   ┆       │
│     ┆     ┆ str ┆ t[s ┆   ┆ --- ┆     ┆       ┆       │
│     ┆     ┆     ┆ tr] ┆   ┆ i32 ┆     ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪═════╪═════╪═══════╪═══════╡
│ htt ┆ Lio ┆ Arg ┆ ["R ┆ … ┆ 202 ┆ FC  ┆ 443   ┆ 1938  │
│ ps: ┆ nel ┆ ent ┆ W", ┆   ┆ 1   ┆ Bar ┆       ┆       │
│ //c ┆ Mes ┆ ina ┆ "ST ┆   ┆     ┆ cel ┆       ┆       │
│ dn. ┆ si  ┆     ┆ ",  ┆   ┆     ┆ ona ┆       ┆       │
│ sof ┆     ┆     ┆ "CF ┆   ┆     ┆     ┆       ┆       │
│ ifa ┆     ┆     ┆ "]  ┆   ┆     ┆     ┆       ┆       │
│ .co ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ m/p ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ lay ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ ers ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ …   ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ htt ┆ C.  ┆ Por ┆ ["S ┆ … ┆ 202 ┆ Juv ┆ 448   ┆ 1872  │
│ ps: ┆ Ron ┆ tug ┆ T", ┆   ┆ 2   ┆ ent ┆       ┆       │
│ //c ┆ ald ┆ al  ┆ "LW ┆   ┆     ┆ us  ┆       ┆       │
│ dn. ┆ o   ┆     ┆ "]  ┆   ┆     ┆     ┆       ┆       │
│ sof ┆ dos ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ ifa ┆ San ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ .co ┆ tos ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ m/p ┆ Ave ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ lay ┆ iro ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ ers ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ …   ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ htt ┆ Jan ┆ Slo ┆ ["G ┆ … ┆ 202 ┆ Atl ┆ 208   ┆ 1213  │
│ ps: ┆ Obl ┆ ven ┆ K"] ┆   ┆ 3   ┆ éti ┆       ┆       │
│ //c ┆ ak  ┆ ia  ┆     ┆   ┆     ┆ co  ┆       ┆       │
│ dn. ┆     ┆     ┆     ┆   ┆     ┆ Mad ┆       ┆       │
│ sof ┆     ┆     ┆     ┆   ┆     ┆ rid ┆       ┆       │
│ ifa ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ .co ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ m/p ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ lay ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ ers ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ …   ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ htt ┆ Kev ┆ Bel ┆ ["C ┆ … ┆ 202 ┆ Man ┆ 499   ┆ 1987  │
│ ps: ┆ in  ┆ giu ┆ AM" ┆   ┆ 3   ┆ che ┆       ┆       │
│ //c ┆ De  ┆ m   ┆ ,   ┆   ┆     ┆ ste ┆       ┆       │
│ dn. ┆ Bru ┆     ┆ "CM ┆   ┆     ┆ r   ┆       ┆       │
│ sof ┆ yne ┆     ┆ "]  ┆   ┆     ┆ Cit ┆       ┆       │
│ ifa ┆     ┆     ┆     ┆   ┆     ┆ y   ┆       ┆       │
│ .co ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ m/p ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ lay ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ ers ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ …   ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ htt ┆ Ney ┆ Bra ┆ ["L ┆ … ┆ 202 ┆ Par ┆ 449   ┆ 1911  │
│ ps: ┆ mar ┆ zil ┆ W", ┆   ┆ 2   ┆ is  ┆       ┆       │
│ //c ┆ da  ┆     ┆ "CA ┆   ┆     ┆ Sai ┆       ┆       │
│ dn. ┆ Sil ┆     ┆ M"] ┆   ┆     ┆ nt- ┆       ┆       │
│ sof ┆ va  ┆     ┆     ┆   ┆     ┆ Ger ┆       ┆       │
│ ifa ┆ San ┆     ┆     ┆   ┆     ┆ mai ┆       ┆       │
│ .co ┆ tos ┆     ┆     ┆   ┆     ┆ n   ┆       ┆       │
│ m/p ┆ Jr. ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ lay ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ ers ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
│ …   ┆     ┆     ┆     ┆   ┆     ┆     ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴─────┴─────┴───────┴───────┘

In [2]:
df.schema

Schema([('photoUrl', String),
        ('LongName', String),
        ('Nationality', String),
        ('Positions', List(String)),
        ('Name', String),
        ('Age', Int64),
        ('OVA', Int64),
        ('POT', Int64),
        ('ID', Int64),
        ('Height', Int32),
        ('Weight', Int32),
        ('foot', String),
        ('BOV', Int64),
        ('BP', String),
        ('Growth', Int64),
        ('Joined', Date),
        ('Loan Date End', Date),
        ('Value', Int32),
        ('Wage', Int32),
        ('Release Clause', Int32),
        ('Total Attacking', Int64),
        ('Crossing', Int64),
        ('Finishing', Int64),
        ('Heading Accuracy', Int64),
        ('Short Passing', Int64),
        ('Volleys', Int64),
        ('Total Skill', Int64),
        ('Dribbling', Int64),
        ('Curve', Int64),
        ('FK Accuracy', Int64),
        ('Long Passing', Int64),
        ('Ball Control', Int64),
        ('Total Movement', Int64),
        ('Acceleration', Int64),
        ('Sprint Speed', Int64),
        ('Agility', Int64),
        ('Reactions', Int64),
        ('Balance', Int64),
        ('Total Power', Int64),
        ('Shot Power', Int64),
        ('Jumping', Int64),
        ('Stamina', Int64),
        ('Strength', Int64),
        ('Long Shots', Int64),
        ('Aggression', Int64),
        ('Interceptions', Int64),
        ('Positioning', Int64),
        ('Vision', Int64),
        ('Penalties', Int64),
        ('Composure', Int64),
        ('Total Defending', Int64),
        ('Marking', Int64),
        ('Standing Tackle', Int64),
        ('Sliding Tackle', Int64),
        ('Total Goalkeeping', Int64),
        ('GK Diving', Int64),
        ('GK Handling', Int64),
        ('GK Kicking', Int64),
        ('GK Positioning', Int64),
        ('GK Reflexes', Int64),
        ('Total Base Stats', Int64),
        ('W/F', Int32),
        ('SM', Int32),
        ('A/W', String),
        ('D/W', String),
        ('IR', Int32),
        ('PAC', Int64),
        ('SHO', Int64),
        ('PAS', Int64),
        ('DRI', Int64),
        ('DEF', Int64),
        ('PHY', Int64),
        ('Hits', Int32),
        ('Contract Started', Int32),
        ('Contract Ends', Int32),
        ('Team', String),
        ('Total Mentality', Int64),
        ('Total Stats', Int64)])

In [3]:
df.select(
    pl.col(pl.NUMERIC_DTYPES).max()
)

C:\Users\xavie\AppData\Local\Temp\ipykernel_20312\2093371838.py:2: DeprecationWarning: `NUMERIC_DTYPES` was deprecated in version 1.0.0. Define your own data type groups or use the `polars.selectors` module for selecting columns of a certain data type.
  pl.col(pl.NUMERIC_DTYPES).max()

shape: (1, 66)
┌─────┬─────┬─────┬─────┬───┬─────┬─────┬───────┬───────┐
│ Age ┆ OVA ┆ POT ┆ ID  ┆ … ┆ Con ┆ Con ┆ Total ┆ Total │
│ --- ┆ --- ┆ --- ┆ --- ┆   ┆ tra ┆ tra ┆ Menta ┆ Stats │
│ i64 ┆ i64 ┆ i64 ┆ i64 ┆   ┆ ct  ┆ ct  ┆ lity  ┆ ---   │
│     ┆     ┆     ┆     ┆   ┆ Sta ┆ End ┆ ---   ┆ i64   │
│     ┆     ┆     ┆     ┆   ┆ rte ┆ s   ┆ i64   ┆       │
│     ┆     ┆     ┆     ┆   ┆ d   ┆ --- ┆       ┆       │
│     ┆     ┆     ┆     ┆   ┆ --- ┆ i32 ┆       ┆       │
│     ┆     ┆     ┆     ┆   ┆ i32 ┆     ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪═════╪═════╪═══════╪═══════╡
│ 53  ┆ 93  ┆ 95  ┆ 259 ┆ … ┆ 202 ┆ 202 ┆ 502   ┆ 1992  │
│     ┆     ┆     ┆ 216 ┆   ┆ 0   ┆ 8   ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴─────┴─────┴───────┴───────┘

In [4]:
df.select(
    pl.col(pl.NUMERIC_DTYPES).min()
)

C:\Users\xavie\AppData\Local\Temp\ipykernel_20312\2803842259.py:2: DeprecationWarning: `NUMERIC_DTYPES` was deprecated in version 1.0.0. Define your own data type groups or use the `polars.selectors` module for selecting columns of a certain data type.
  pl.col(pl.NUMERIC_DTYPES).min()

shape: (1, 66)
┌─────┬─────┬─────┬─────┬───┬─────┬─────┬───────┬───────┐
│ Age ┆ OVA ┆ POT ┆ ID  ┆ … ┆ Con ┆ Con ┆ Total ┆ Total │
│ --- ┆ --- ┆ --- ┆ --- ┆   ┆ tra ┆ tra ┆ Menta ┆ Stats │
│ i64 ┆ i64 ┆ i64 ┆ i64 ┆   ┆ ct  ┆ ct  ┆ lity  ┆ ---   │
│     ┆     ┆     ┆     ┆   ┆ Sta ┆ End ┆ ---   ┆ i64   │
│     ┆     ┆     ┆     ┆   ┆ rte ┆ s   ┆ i64   ┆       │
│     ┆     ┆     ┆     ┆   ┆ d   ┆ --- ┆       ┆       │
│     ┆     ┆     ┆     ┆   ┆ --- ┆ i32 ┆       ┆       │
│     ┆     ┆     ┆     ┆   ┆ i32 ┆     ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪═════╪═════╪═══════╪═══════╡
│ 16  ┆ 47  ┆ 47  ┆ 41  ┆ … ┆ 199 ┆ 202 ┆ 63    ┆ 608   │
│     ┆     ┆     ┆     ┆   ┆ 8   ┆ 0   ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴─────┴─────┴───────┴───────┘

In [5]:
attacking_cols = [
    "Crossing",
    "Finishing",
    "Heading Accuracy",
    "Short Passing",
    "Volleys",
]

df = df.with_columns(
    pl.sum_horizontal(attacking_cols).alias("calculated_total_attacking")
)

invalid = df.filter(
    pl.col("Total Attacking") != pl.col("calculated_total_attacking")
)

print(f"Invalid total attacking rows: {invalid.height}")

Invalid total attacking rows: 0

In [6]:
skill_cols = [
    "Dribbling",
    "Curve",
    "FK Accuracy",
    "Long Passing",
    "Ball Control",
    
]

df = df.with_columns(
    pl.sum_horizontal(skill_cols).alias("calculated_total_skill")
)

invalid = df.filter(
    pl.col("Total Skill") != pl.col("calculated_total_skill")
)
print(f"Invalid total skill rows: {invalid.height}")

Invalid total skill rows: 0

In [7]:
movement_cols = [
    "Acceleration",
    "Sprint Speed",
    "Agility",
    "Reactions",
    "Balance",
    
]

df = df.with_columns(
    pl.sum_horizontal(movement_cols).alias("calculated_total_movement")
)

invalid = df.filter(
    pl.col("Total Movement") != pl.col("calculated_total_movement")
)
print(f"Invalid total movement rows: {invalid.height}")

Invalid total movement rows: 0

In [8]:
power_cols = [
    "Shot Power",
    "Jumping",
    "Stamina",
    "Strength",
    "Long Shots",
    
]

df = df.with_columns(
    pl.sum_horizontal(power_cols).alias("calculated_total_power")
)

invalid = df.filter(
    pl.col("Total Power") != pl.col("calculated_total_power")
)
print(f"Invalid total power rows: {invalid.height}")

Invalid total power rows: 0

In [9]:
#mentality is missing a column(Attack position) must calculate total mentality based on existing columns. Same for total stats.
mentality_cols = [
    "Aggression",
    "Interceptions",
    "Positioning",
    "Vision",
    "Penalties",
    "Composure"
    
]

df = df.with_columns(
    pl.sum_horizontal(mentality_cols).alias("calculated_total_mentality")
)

invalid = df.filter(
    pl.col("Total Mentality") != pl.col("calculated_total_mentality")
)
print(f"Invalid total mentality rows: {invalid.height}")

Invalid total mentality rows: 0

In [10]:
defending_cols = [
    "Marking",
    "Standing Tackle",
    "Sliding Tackle"
]

df = df.with_columns(
    pl.sum_horizontal(defending_cols).alias("calculated_total_defending")
)

invalid = df.filter(
    pl.col("Total Defending") != pl.col("calculated_total_defending")
)
print(f"Invalid total defending rows: {invalid.height}")

Invalid total defending rows: 0

In [11]:
goalkeeping_cols = [
    "GK Diving",
    "GK Handling",
    "GK Kicking",
    "GK Positioning",
    "GK Reflexes"
]

df = df.with_columns(
    pl.sum_horizontal(goalkeeping_cols).alias("calculated_total_goalkeeping")
)

invalid = df.filter(
    pl.col("Total Goalkeeping") != pl.col("calculated_total_goalkeeping")
)
print(f"Invalid total goalkeeping rows: {invalid.height}")

Invalid total goalkeeping rows: 0

In [12]:
baseStats_cols = [
    "PAC",
    "SHO",
    "PAS",
    "DRI",
    "DEF",
    "PHY"
]

df = df.with_columns(
    pl.sum_horizontal(baseStats_cols).alias("calculated_total_baseStats")
)

invalid = df.filter(
    pl.col("Total Base Stats") != pl.col("calculated_total_baseStats")
)
print(f"Invalid total base stats rows: {invalid.height}")

Invalid total base stats rows: 0

In [13]:
stats_cols = [
    "Total Attacking",
    "Total Skill",
    "Total Movement",
    "Total Mentality",
    "Total Defending",
    "Total Goalkeeping"
]
df = df.with_columns(
    pl.sum_horizontal(stats_cols).alias("calculated_total_stats")
)

invalid = df.filter(
    pl.col("Total Stats") != pl.col("calculated_total_stats")
)
print(f"Invalid total stats rows: {invalid.height}")

Invalid total stats rows: 0